input_dir: /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/pandora/det_var/nominal
#output_dir: /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/pandora/det_var/nominal/v8
output_dir: /pnfs/sbnd/scratch/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/pandora/det_var/nominal/v8

jobs:
  - name: nosyst_nocuts_recomb
    enabled: true
    description: INCLUDE_WEIGHTS=False, SLIM=False, UPDATE_RECOMB=True
    base_config: analysis_village.numuincl.configs.base
    dfs:
      - makedf.makedf.make_hdrdf
      - makedf.makedf.make_mcnudf
      - analysis_village.numuincl.makedf1muX.make_pandora_evtdf_processed
      - analysis_village.numuincl.makedf1muX.make_custom_trkdf
    names: [hdr, mcnu, evt_pand, trk]
    input_list: nominal_sorted.list
    #input_files: /pnfs/sbn/data_add/sbn_nd/aurora/mc/v10_06_00_10/cv/000009/000096/reco2-637d-d21a-2167-73ab.flat.caf.root
    output: detvar_nominal_nosyst_nocuts_recomb_large
    settings:
      INCLUDE_WEIGHTS: false
      SLIM: false
      UPDATE_RECOMB: true
      VERBOSE: false
    args:
      ngrid: 1000
      ncpu: -1
      nfile: -1